query EMSIChannelPosts($channelID: ID!, $limit: Int = 30, $cursor: String) {
  channelPosts(channelID: $channelID, limit: $limit, cursor: $cursor) {
    posts {
      id
      legacyPostID
      channelID
      parentPostID
      author {
        id
        legacyUserID
        username
        usernameColor
        pictureURL
      }
      content
      attachmentURL
      thumbnailURL
      blurhash
      width
      height
      replyCount
      replyPreview {
        id
        legacyPostID
        channelID
        parentPostID
        author {
          id
          legacyUserID
          username
          usernameColor
          pictureURL
        }
        content
        attachmentURL
        thumbnailURL
        blurhash
        width
        height
        replyCount
        reactionSummary {
          emojiID
          key
          unified
          url
          count
          updatedAt
        }
        createdAt
        updatedAt
      }
      reactionSummary {
        emojiID
        key
        unified
        url
        count
        updatedAt
      }
      createdAt
      updatedAt
    }
    nextCursor
  }
}
